### PR TITLE
add a method to merge barrel layers

### PR DESCRIPTION
**Pull request by tong-qiu**
Add a method in the `detector` class to merge positive parts and negative parts of barrel layers. A merged barrel layer is needed to avoid particles getting stuck in the shared boundary between the positive part and negative part during transportation.

### CODE REVIEW

**Comment by jbeirer** [comment]
Hi @tong-qiu,

many thanks for this! Can you run `make check` and push with the changes?

Also, could you attach the the resulting gdml file for ATLAS?

Cheers,

Joshua

**Comment by tong-qiu** [comment]
Hi @jbeirer,

I have executed `make check` and moved the method call to `process`.

The resulting gdml file: [processed.gdml.txt](https://github.com/user-attachments/files/16800286/processed.gdml.txt).

The graph showing photon transportation:

particle_transport

Cheers,
Tong Qiu

**Comment by jbeirer** [comment]
Hi @tong-qiu,

I took a look at how the geometry looks in your gdml file:

Screenshot 2024-08-29 at 17 35 09

We are getting these significant gaps in the endcap region. See how it should like here: https://github.com/jbeirer/pygeosimplify/pull/135 (on the right plot). How are you generating the file? To do so, we should use all layers (0-23) except TileGap3 (17). 

To make the image yourself with geomodel you can add

``` xml
 <materials>
       <isotope N="1" Z="1" name="H">
        <atom unit="g/mole" value="0"/>
        </isotope>
        <element name="H">
        <fraction n="1" ref="H"/>
        </element>
        <material name="G4_Galactic">
            <D unit="g/cm3" value="0"/>
            <fraction n="1" ref="H"/>
        </material>
    <materials/>
``` 

to the top of the file and then:

```
gdml2gm -f processed.gdml -o processed.db
gmex processed.db
```

Cheers,

Joshua

**Comment by tong-qiu** [comment]
Hi @jbeirer,

I didn't know that layer 17 needs to be excluded. Here is the new file with layer 17 excluded:  [processed.gdml.txt](https://github.com/user-attachments/files/16806359/processed.gdml.txt). I can't make the image because I can't install GeoModel unfortunately.

I have also updated the tests.

Cheers,
Tong Qiu

**Review by jbeirer — APPROVED** [review]

**Pull request merged**
